---
stages:
  - pull_sn_hw
  - package
  - trigger_downstream

variables:
  SN_HW_REPO_BRANCH: main
pull_sn_hw:
  stage: pull_sn_hw
  image: ubuntu:focal
  variables:
    ESNET_SMARTNIC_HWAPI_URL: "$CI_API_V4_URL/projects/ht%2Fhightouch-xilinx-dp/jobs/artifacts/$SN_HW_REPO_BRANCH/download?job_token=$CI_JOB_TOKEN&job=export_hwapi"
    GIT_SUBMODULE_STRATEGY: none
  before_script:
    - apt update -y
    - ln -fs /usr/share/zoneinfo/America/Toronto /etc/localtime
    - apt install -y --no-install-recommends wget ca-certificates
  script:
    - echo "Downloading smartnic hwapi"
    - mkdir -p ./sn-hw/
    - |
      wget \
        --no-verbose \
        --trust-server-names \
        --content-disposition \
        --directory-prefix=./sn-hw \
        $ESNET_SMARTNIC_HWAPI_URL
    - ls ./sn-hw/*.zip | sed -re 's/^.*\.([0-9]+)\.zip$/SN_HW_VER=\1/' >> hwapi.env
    - cat hwapi.env
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    paths:
      - sn-hw
    expire_in: 3 month
    reports:
      dotenv:
        hwapi.env
  needs: []

.compose_package:
  stage: package
  image: docker:20.10.10
  services:
    - docker:20.10.10-dind
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    OS_CODENAME: focal
    SN_FW_VER: ${CI_PIPELINE_ID}
    DOCKER_COMPOSE_URL: https://dispense.es.net/Linux/github-mirrors/docker/compose/v2.1.1/docker-compose-linux-x86_64
    #COMPOSE_PROJECT_NAME: ${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-${CI_JOB_ID}
  before_script:
    # Install docker compose v2 plugin
    - mkdir -p /usr/local/lib/docker/cli-plugins
    - wget  -O /usr/local/lib/docker/cli-plugins/docker-compose ${DOCKER_COMPOSE_URL}
    - chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
    - docker compose version
  script:
    - |
      cat <<_EOF > .env
      SN_HW_VER=${SN_HW_VER}
      SN_FW_VER=${SN_FW_VER}
      OS_CODENAME=${OS_CODENAME}
      _EOF
    - cat .env
    - docker compose config
    - docker compose ps
    - docker ps
    - docker compose build sn-fw-pkg
    - docker compose run --rm sn-fw-pkg
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    paths:
      - sn-stack
    expire_in: 3 month
  needs:
    - pull_sn_hw

package_bionic:
  extends:
    - .compose_package
  variables:
    OS_CODENAME: bionic

package_focal:
  extends:
    - .compose_package
  variables:
    OS_CODENAME: focal

trigger_downstream:
  stage: trigger_downstream
  # Make sure the downstream pipeline doesn't inherit any of the global env vars from this project
  inherit:
    variables: false
  trigger:
    project: ht/hightouch-xilinx
    branch: main
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
