---
stages:
  - pull_smartnic_hwapi
  - build
  - package
  - trigger_downstream

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HT_SWDEV_DOCKER_IMAGE: hub.es.net:5000/hightouch-swdev-docker:v1.11
  ESNET_SMARTNIC_HWAPI_URL: "$CI_API_V4_URL/projects/ht%2Fhightouch-xilinx-dp/jobs/artifacts/main/download?job_token=$CI_JOB_TOKEN&job=export_hwapi"

pull_smartnic_hwapi_job:
  stage: pull_smartnic_hwapi
  image: ${HT_SWDEV_DOCKER_IMAGE}-focal
  script:
    - echo "Downloading smartnic hwapi"
    - TMPDIR="$(mktemp --directory)"
    - wget --no-verbose --trust-server-names --content-disposition --directory-prefix="$TMPDIR" $ESNET_SMARTNIC_HWAPI_URL
    - ls -l ${TMPDIR}/*.zip
    - mkdir -p subprojects/packagefiles
    - mv ${TMPDIR}/*.zip subprojects/packagefiles/esnet-smartnic-hwapi.zip
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    paths:
      - subprojects/packagefiles/esnet-smartnic-hwapi.zip
    expire_in: 3 month
  needs: []

.build:
  stage: build
  image: ${HT_SWDEV_DOCKER_IMAGE}-${OS_CODENAME}
  script:
    - meson build-${OS_CODENAME}
    - ninja -C build-${OS_CODENAME}
  artifacts:
    paths:
      - build-${OS_CODENAME}
    expire_in: 3 month
  needs:
    - pull_smartnic_hwapi_job

.package:
  stage: package
  image: ubuntu:$OS_CODENAME
  variables:
    DEBEMAIL: "smartnic@es.net"
    DEBFULLNAME: "ESnet SmartNIC Developers"
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - |
      cat <<_EOF > /etc/apt/sources.list
      deb http://linux.mirrors.es.net/ubuntu ${OS_CODENAME} main restricted
      deb http://linux.mirrors.es.net/ubuntu ${OS_CODENAME}-updates main restricted
      deb http://linux.mirrors.es.net/ubuntu ${OS_CODENAME} universe
      deb http://linux.mirrors.es.net/ubuntu ${OS_CODENAME}-updates universe
      deb http://linux.mirrors.es.net/ubuntu ${OS_CODENAME} multiverse
      deb http://linux.mirrors.es.net/ubuntu ${OS_CODENAME}-updates multiverse
      deb http://linux.mirrors.es.net/ubuntu ${OS_CODENAME}-backports main restricted universe multiverse
      deb http://security.ubuntu.com/ubuntu ${OS_CODENAME}-security main restricted
      deb http://security.ubuntu.com/ubuntu ${OS_CODENAME}-security universe
      deb http://security.ubuntu.com/ubuntu ${OS_CODENAME}-security multiverse
      _EOF
    - apt update -y
    - ln -fs /usr/share/zoneinfo/America/Toronto /etc/localtime
    - |
      apt install -y --no-install-recommends \
        build-essential \
        cdbs \
        devscripts \
        equivs \
        fakeroot \
        libdistro-info-perl
    - |
      apt install -y --no-install-recommends \
        python3-pip \
        python3-setuptools
    - pip3 install meson
    - pip3 install pyyaml-include
    - pip3 install yq
  script:
    - |
      mk-build-deps --install \
        --tool 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' \
        debian/control
    - rm -f debian/changelog
    - |
      dch --create \
        --package esnet-smartnic \
        --newversion 1.0.0-${CI_PIPELINE_ID} \
        --distribution ${OS_CODENAME} \
        --urgency medium debian/changelog
    - dpkg-buildpackage --build=binary -us -uc
    - mkdir -p debs/${OS_CODENAME}
    # Output of debian builds goes to '..' and can't currently be changed
    # These need to be mv's to ensure that we minimize pollution in the CI build env
    # We also need to be careful to mv only our output files to not interfere with other builds
    #   See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=657401
    #   See: https://pmhahn.github.io/debian-oot-build/
    - mv ../*-${CI_PIPELINE_ID}_*.{buildinfo,changes,deb,ddeb} ./debs/${OS_CODENAME}
  artifacts:
    paths:
      - debs
    expire_in: 3 month
  needs:
    - pull_smartnic_hwapi_job

.base_os_1804:
  variables:
    OS_CODENAME: bionic

.base_os_2004:
  variables:
    OS_CODENAME: focal

build_1804:
  extends:
    - .base_os_1804
    - .build
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"

build_2004:
  extends:
    - .base_os_2004
    - .build
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"

package_1804:
  extends:
    - .base_os_1804
    - .package
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"

package_2004:
  extends:
    - .base_os_2004
    - .package
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"

trigger_downstream_job:
  stage: trigger_downstream
  # Make sure the downstream pipeline doesn't inherit any of the global env vars from this project
  inherit:
    variables: false
  trigger:
    project: ht/hightouch-xilinx
    branch: main
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
