---
stages:
  - pull_smartnic_hwapi
  - build
  - package

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HT_SWDEV_DOCKER_IMAGE: hub.es.net:5000/hightouch-swdev-docker:v1.8
  ESNET_SMARTNIC_HWAPI_URL: "$CI_API_V4_URL/projects/ht%2Fhightouch-xilinx-dp/jobs/artifacts/main/download?job_token=$CI_JOB_TOKEN&job=export_hwapi"

pull_smartnic_hwapi_job:
  stage: pull_smartnic_hwapi
  image: ${HT_SWDEV_DOCKER_IMAGE}-focal
  script:
    - mkdir -p subprojects/packagefiles
    - wget --no-verbose -O subprojects/packagefiles/esnet-smartnic-hwapi.zip $ESNET_SMARTNIC_HWAPI_URL
  artifacts:
    paths:
      - subprojects/packagefiles/esnet-smartnic-hwapi.zip
    expire_in: 1 week
  needs: []

build_job:
  stage: build
  image: ${HT_SWDEV_DOCKER_IMAGE}-focal
  script:
    - meson build
    - ninja -C build
  artifacts:
    paths:
      - build
  needs:
    - pull_smartnic_hwapi_job

package_job:
  stage: package
  image: ubuntu:focal
  variables:
    DEBEMAIL: "smartnic@es.net"
    DEBFULLNAME: "ESnet SmartNIC Developers"
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - |
      cat <<_EOF > /etc/apt/sources.list
      deb http://linux.mirrors.es.net/ubuntu focal main restricted
      deb http://linux.mirrors.es.net/ubuntu focal-updates main restricted
      deb http://linux.mirrors.es.net/ubuntu focal universe
      deb http://linux.mirrors.es.net/ubuntu focal-updates universe
      deb http://linux.mirrors.es.net/ubuntu focal multiverse
      deb http://linux.mirrors.es.net/ubuntu focal-updates multiverse
      deb http://linux.mirrors.es.net/ubuntu focal-backports main restricted universe multiverse
      deb http://security.ubuntu.com/ubuntu focal-security main restricted
      deb http://security.ubuntu.com/ubuntu focal-security universe
      deb http://security.ubuntu.com/ubuntu focal-security multiverse
      _EOF
    - apt update -y
    - ln -fs /usr/share/zoneinfo/America/Toronto /etc/localtime
    - |
      apt install -y --no-install-recommends \
        build-essential \
        cdbs \
        devscripts \
        equivs \
        fakeroot \
        libdistro-info-perl
    - |
      apt install -y --no-install-recommends \
        python3-pip
    - pip3 install meson
    - pip3 install pyyaml-include
    - pip3 install yq
  script:
    - |
      mk-build-deps --install \
        --tool 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' \
        debian/control
    - rm -f debian/changelog
    - |
      dch --create \
        --package esnet-smartnic \
        --newversion 1.0.0-${CI_PIPELINE_ID} \
        --distribution focal \
        --urgency medium debian/changelog
    - dpkg-buildpackage --build=binary -us -uc
    - mkdir debs
    - cp ../*.deb ../*.ddeb ../*.buildinfo ../*.changes ./debs
  artifacts:
    paths:
      - debs
  needs:
    - pull_smartnic_hwapi_job

