/*
 *  Register definitions for block: sysmon_2
 *
 *  Xilinx UltraScale Architecture System Monitor
 *  Ref: UG580: https://www.xilinx.com/support/documentation/user_guides/ug580-ultrascale-sysmon.pdf
 *  Ref: PG184: https://www.xilinx.com/support/documentation/ip_documentation/system_management_wiz/v1_3/pg185-system-management-wiz.pdf
 *  
 *  The SYSMON includes an analog-to-digital converter (ADC) as well as on-chip sensors
 *  that can be used to sample external voltages and monitor on-die operating conditions,
 *  such as temperature and supply voltage levels.
 *  
 *
 *  NOTE: This file was autogenerated by regio
 */

#if !defined(INCLUDE_SYSMON_2_BLOCK_H)
#define INCLUDE_SYSMON_2_BLOCK_H 1

#include <stdint.h>
#include <stdbool.h>

/*
 * status
 */

union sysmon_2_status {
  struct {
      uint32_t ch                              :  6;   //   [ 5: 0]
      uint32_t eoc                             :  1;   //   [    6]
      uint32_t eos                             :  1;   //   [    7]
      uint32_t busy                            :  1;   //   [    8]
      uint32_t jtag_locked                     :  1;   //   [    9]
      uint32_t jtag_modified                   :  1;   //   [   10]
      uint32_t jtag_busy                       :  1;   //   [   11]
  };
  uint32_t _v;
};

#define SYSMON_2_STATUS_CH_MASK                             0x0000003F
#define SYSMON_2_STATUS_EOC_MASK                            0x00000040
#define SYSMON_2_STATUS_EOS_MASK                            0x00000080
#define SYSMON_2_STATUS_BUSY_MASK                           0x00000100
#define SYSMON_2_STATUS_JTAG_LOCKED_MASK                    0x00000200
#define SYSMON_2_STATUS_JTAG_MODIFIED_MASK                  0x00000400
#define SYSMON_2_STATUS_JTAG_BUSY_MASK                      0x00000800

#define SYSMON_2_STATUS_CH_SHIFT                                     0
#define SYSMON_2_STATUS_EOC_SHIFT                                    6
#define SYSMON_2_STATUS_EOS_SHIFT                                    7
#define SYSMON_2_STATUS_BUSY_SHIFT                                   8
#define SYSMON_2_STATUS_JTAG_LOCKED_SHIFT                            9
#define SYSMON_2_STATUS_JTAG_MODIFIED_SHIFT                         10
#define SYSMON_2_STATUS_JTAG_BUSY_SHIFT                             11

/*
 * alarm_output_status
 */

union sysmon_2_alarm_output_status {
  struct {
      uint32_t over_temperature                :  1;   //   [    0]
      uint32_t temperature                     :  1;   //   [    1]
      uint32_t vccint                          :  1;   //   [    2]
      uint32_t vccaux                          :  1;   //   [    3]
      uint32_t vccbram                         :  1;   //   [    4]
      uint32_t rsvd0                           :  3;   //   [ 7: 5]
      uint32_t any                             :  1;   //   [    8]
      uint32_t vuser0                          :  1;   //   [    9]
      uint32_t vuser1                          :  1;   //   [   10]
      uint32_t vuser2                          :  1;   //   [   11]
      uint32_t vuser3                          :  1;   //   [   12]
      uint32_t rsvd1                           :  3;   //   [15:13]
      uint32_t any_vuser                       :  1;   //   [   16]
  };
  uint32_t _v;
};

#define SYSMON_2_ALARM_OUTPUT_STATUS_OVER_TEMPERATURE_MASK  0x00000001
#define SYSMON_2_ALARM_OUTPUT_STATUS_TEMPERATURE_MASK       0x00000002
#define SYSMON_2_ALARM_OUTPUT_STATUS_VCCINT_MASK            0x00000004
#define SYSMON_2_ALARM_OUTPUT_STATUS_VCCAUX_MASK            0x00000008
#define SYSMON_2_ALARM_OUTPUT_STATUS_VCCBRAM_MASK           0x00000010
#define SYSMON_2_ALARM_OUTPUT_STATUS_RSVD0_MASK             0x000000E0
#define SYSMON_2_ALARM_OUTPUT_STATUS_ANY_MASK               0x00000100
#define SYSMON_2_ALARM_OUTPUT_STATUS_VUSER0_MASK            0x00000200
#define SYSMON_2_ALARM_OUTPUT_STATUS_VUSER1_MASK            0x00000400
#define SYSMON_2_ALARM_OUTPUT_STATUS_VUSER2_MASK            0x00000800
#define SYSMON_2_ALARM_OUTPUT_STATUS_VUSER3_MASK            0x00001000
#define SYSMON_2_ALARM_OUTPUT_STATUS_RSVD1_MASK             0x0000E000
#define SYSMON_2_ALARM_OUTPUT_STATUS_ANY_VUSER_MASK         0x00010000

#define SYSMON_2_ALARM_OUTPUT_STATUS_OVER_TEMPERATURE_SHIFT           0
#define SYSMON_2_ALARM_OUTPUT_STATUS_TEMPERATURE_SHIFT               1
#define SYSMON_2_ALARM_OUTPUT_STATUS_VCCINT_SHIFT                    2
#define SYSMON_2_ALARM_OUTPUT_STATUS_VCCAUX_SHIFT                    3
#define SYSMON_2_ALARM_OUTPUT_STATUS_VCCBRAM_SHIFT                   4
#define SYSMON_2_ALARM_OUTPUT_STATUS_RSVD0_SHIFT                     5
#define SYSMON_2_ALARM_OUTPUT_STATUS_ANY_SHIFT                       8
#define SYSMON_2_ALARM_OUTPUT_STATUS_VUSER0_SHIFT                    9
#define SYSMON_2_ALARM_OUTPUT_STATUS_VUSER1_SHIFT                   10
#define SYSMON_2_ALARM_OUTPUT_STATUS_VUSER2_SHIFT                   11
#define SYSMON_2_ALARM_OUTPUT_STATUS_VUSER3_SHIFT                   12
#define SYSMON_2_ALARM_OUTPUT_STATUS_RSVD1_SHIFT                    13
#define SYSMON_2_ALARM_OUTPUT_STATUS_ANY_VUSER_SHIFT                16

/*
 * convst
 */

union sysmon_2_convst {
  struct {
      uint32_t start                           :  1;   //   [    0]
      uint32_t rsvd                            :  1;   //   [    1]
      uint32_t wait_cycle                      : 16;   //   [17: 2]
  };
  uint32_t _v;
};

#define SYSMON_2_CONVST_START_MASK                          0x00000001
#define SYSMON_2_CONVST_RSVD_MASK                           0x00000002
#define SYSMON_2_CONVST_WAIT_CYCLE_MASK                     0x0003FFFC

#define SYSMON_2_CONVST_START_SHIFT                                  0
#define SYSMON_2_CONVST_RSVD_SHIFT                                   1
#define SYSMON_2_CONVST_WAIT_CYCLE_SHIFT                             2

/*
 * sysmon_reset
 */

union sysmon_2_sysmon_reset {
  struct {
      uint32_t reset                           :  1;   //   [    0]
  };
  uint32_t _v;
};

#define SYSMON_2_SYSMON_RESET_RESET_MASK                    0x00000001

#define SYSMON_2_SYSMON_RESET_RESET_SHIFT                            0

/*
 * global_interrupt_enable
 */

union sysmon_2_global_interrupt_enable {
  struct {
      uint32_t rsvd                            : 31;   //   [30: 0]
      uint32_t gier                            :  1;   //   [   31]
  };
  uint32_t _v;
};

#define SYSMON_2_GLOBAL_INTERRUPT_ENABLE_RSVD_MASK          0x7FFFFFFF
#define SYSMON_2_GLOBAL_INTERRUPT_ENABLE_GIER_MASK          0x80000000

#define SYSMON_2_GLOBAL_INTERRUPT_ENABLE_RSVD_SHIFT                  0
#define SYSMON_2_GLOBAL_INTERRUPT_ENABLE_GIER_SHIFT                 31

/*
 * ip_interrupt_status
 */

union sysmon_2_ip_interrupt_status {
  struct {
      uint32_t over_temperature                :  1;   //   [    0]
      uint32_t temperature                     :  1;   //   [    1]
      uint32_t vccint                          :  1;   //   [    2]
      uint32_t vccaux                          :  1;   //   [    3]
      uint32_t eos                             :  1;   //   [    4]
      uint32_t eoc                             :  1;   //   [    5]
      uint32_t jtag_locked                     :  1;   //   [    6]
      uint32_t jtag_modified                   :  1;   //   [    7]
      uint32_t over_temperature_deactive       :  1;   //   [    8]
      uint32_t temperature_deactive            :  1;   //   [    9]
      uint32_t vccbram                         :  1;   //   [   10]
      uint32_t rsvd                            :  3;   //   [13:11]
      uint32_t vuser0                          :  1;   //   [   14]
      uint32_t vuser1                          :  1;   //   [   15]
      uint32_t vuser2                          :  1;   //   [   16]
      uint32_t vuser3                          :  1;   //   [   17]
  };
  uint32_t _v;
};

#define SYSMON_2_IP_INTERRUPT_STATUS_OVER_TEMPERATURE_MASK  0x00000001
#define SYSMON_2_IP_INTERRUPT_STATUS_TEMPERATURE_MASK       0x00000002
#define SYSMON_2_IP_INTERRUPT_STATUS_VCCINT_MASK            0x00000004
#define SYSMON_2_IP_INTERRUPT_STATUS_VCCAUX_MASK            0x00000008
#define SYSMON_2_IP_INTERRUPT_STATUS_EOS_MASK               0x00000010
#define SYSMON_2_IP_INTERRUPT_STATUS_EOC_MASK               0x00000020
#define SYSMON_2_IP_INTERRUPT_STATUS_JTAG_LOCKED_MASK       0x00000040
#define SYSMON_2_IP_INTERRUPT_STATUS_JTAG_MODIFIED_MASK     0x00000080
#define SYSMON_2_IP_INTERRUPT_STATUS_OVER_TEMPERATURE_DEACTIVE_MASK  0x00000100
#define SYSMON_2_IP_INTERRUPT_STATUS_TEMPERATURE_DEACTIVE_MASK  0x00000200
#define SYSMON_2_IP_INTERRUPT_STATUS_VCCBRAM_MASK           0x00000400
#define SYSMON_2_IP_INTERRUPT_STATUS_RSVD_MASK              0x00003800
#define SYSMON_2_IP_INTERRUPT_STATUS_VUSER0_MASK            0x00004000
#define SYSMON_2_IP_INTERRUPT_STATUS_VUSER1_MASK            0x00008000
#define SYSMON_2_IP_INTERRUPT_STATUS_VUSER2_MASK            0x00010000
#define SYSMON_2_IP_INTERRUPT_STATUS_VUSER3_MASK            0x00020000

#define SYSMON_2_IP_INTERRUPT_STATUS_OVER_TEMPERATURE_SHIFT           0
#define SYSMON_2_IP_INTERRUPT_STATUS_TEMPERATURE_SHIFT               1
#define SYSMON_2_IP_INTERRUPT_STATUS_VCCINT_SHIFT                    2
#define SYSMON_2_IP_INTERRUPT_STATUS_VCCAUX_SHIFT                    3
#define SYSMON_2_IP_INTERRUPT_STATUS_EOS_SHIFT                       4
#define SYSMON_2_IP_INTERRUPT_STATUS_EOC_SHIFT                       5
#define SYSMON_2_IP_INTERRUPT_STATUS_JTAG_LOCKED_SHIFT               6
#define SYSMON_2_IP_INTERRUPT_STATUS_JTAG_MODIFIED_SHIFT             7
#define SYSMON_2_IP_INTERRUPT_STATUS_OVER_TEMPERATURE_DEACTIVE_SHIFT           8
#define SYSMON_2_IP_INTERRUPT_STATUS_TEMPERATURE_DEACTIVE_SHIFT           9
#define SYSMON_2_IP_INTERRUPT_STATUS_VCCBRAM_SHIFT                  10
#define SYSMON_2_IP_INTERRUPT_STATUS_RSVD_SHIFT                     11
#define SYSMON_2_IP_INTERRUPT_STATUS_VUSER0_SHIFT                   14
#define SYSMON_2_IP_INTERRUPT_STATUS_VUSER1_SHIFT                   15
#define SYSMON_2_IP_INTERRUPT_STATUS_VUSER2_SHIFT                   16
#define SYSMON_2_IP_INTERRUPT_STATUS_VUSER3_SHIFT                   17

/*
 * ip_interrupt_enable
 */

union sysmon_2_ip_interrupt_enable {
  struct {
      uint32_t over_temperature                :  1;   //   [    0]
      uint32_t temperature                     :  1;   //   [    1]
      uint32_t vccint                          :  1;   //   [    2]
      uint32_t vccaux                          :  1;   //   [    3]
      uint32_t eos                             :  1;   //   [    4]
      uint32_t eoc                             :  1;   //   [    5]
      uint32_t jtag_locked                     :  1;   //   [    6]
      uint32_t jtag_modified                   :  1;   //   [    7]
      uint32_t over_temperature_deactive       :  1;   //   [    8]
      uint32_t temperature_deactive            :  1;   //   [    9]
      uint32_t vccbram                         :  1;   //   [   10]
      uint32_t rsvd                            :  3;   //   [13:11]
      uint32_t vuser0                          :  1;   //   [   14]
      uint32_t vuser1                          :  1;   //   [   15]
      uint32_t vuser2                          :  1;   //   [   16]
      uint32_t vuser3                          :  1;   //   [   17]
  };
  uint32_t _v;
};

#define SYSMON_2_IP_INTERRUPT_ENABLE_OVER_TEMPERATURE_MASK  0x00000001
#define SYSMON_2_IP_INTERRUPT_ENABLE_TEMPERATURE_MASK       0x00000002
#define SYSMON_2_IP_INTERRUPT_ENABLE_VCCINT_MASK            0x00000004
#define SYSMON_2_IP_INTERRUPT_ENABLE_VCCAUX_MASK            0x00000008
#define SYSMON_2_IP_INTERRUPT_ENABLE_EOS_MASK               0x00000010
#define SYSMON_2_IP_INTERRUPT_ENABLE_EOC_MASK               0x00000020
#define SYSMON_2_IP_INTERRUPT_ENABLE_JTAG_LOCKED_MASK       0x00000040
#define SYSMON_2_IP_INTERRUPT_ENABLE_JTAG_MODIFIED_MASK     0x00000080
#define SYSMON_2_IP_INTERRUPT_ENABLE_OVER_TEMPERATURE_DEACTIVE_MASK  0x00000100
#define SYSMON_2_IP_INTERRUPT_ENABLE_TEMPERATURE_DEACTIVE_MASK  0x00000200
#define SYSMON_2_IP_INTERRUPT_ENABLE_VCCBRAM_MASK           0x00000400
#define SYSMON_2_IP_INTERRUPT_ENABLE_RSVD_MASK              0x00003800
#define SYSMON_2_IP_INTERRUPT_ENABLE_VUSER0_MASK            0x00004000
#define SYSMON_2_IP_INTERRUPT_ENABLE_VUSER1_MASK            0x00008000
#define SYSMON_2_IP_INTERRUPT_ENABLE_VUSER2_MASK            0x00010000
#define SYSMON_2_IP_INTERRUPT_ENABLE_VUSER3_MASK            0x00020000

#define SYSMON_2_IP_INTERRUPT_ENABLE_OVER_TEMPERATURE_SHIFT           0
#define SYSMON_2_IP_INTERRUPT_ENABLE_TEMPERATURE_SHIFT               1
#define SYSMON_2_IP_INTERRUPT_ENABLE_VCCINT_SHIFT                    2
#define SYSMON_2_IP_INTERRUPT_ENABLE_VCCAUX_SHIFT                    3
#define SYSMON_2_IP_INTERRUPT_ENABLE_EOS_SHIFT                       4
#define SYSMON_2_IP_INTERRUPT_ENABLE_EOC_SHIFT                       5
#define SYSMON_2_IP_INTERRUPT_ENABLE_JTAG_LOCKED_SHIFT               6
#define SYSMON_2_IP_INTERRUPT_ENABLE_JTAG_MODIFIED_SHIFT             7
#define SYSMON_2_IP_INTERRUPT_ENABLE_OVER_TEMPERATURE_DEACTIVE_SHIFT           8
#define SYSMON_2_IP_INTERRUPT_ENABLE_TEMPERATURE_DEACTIVE_SHIFT           9
#define SYSMON_2_IP_INTERRUPT_ENABLE_VCCBRAM_SHIFT                  10
#define SYSMON_2_IP_INTERRUPT_ENABLE_RSVD_SHIFT                     11
#define SYSMON_2_IP_INTERRUPT_ENABLE_VUSER0_SHIFT                   14
#define SYSMON_2_IP_INTERRUPT_ENABLE_VUSER1_SHIFT                   15
#define SYSMON_2_IP_INTERRUPT_ENABLE_VUSER2_SHIFT                   16
#define SYSMON_2_IP_INTERRUPT_ENABLE_VUSER3_SHIFT                   17

/*
 * temperature
 */

union sysmon_2_temperature {
  struct {
      uint32_t rsvd                            :  6;   //   [ 5: 0]
      uint32_t adc                             : 10;   //   [15: 6]
  };
  uint32_t _v;
};

#define SYSMON_2_TEMPERATURE_RSVD_MASK                      0x0000003F
#define SYSMON_2_TEMPERATURE_ADC_MASK                       0x0000FFC0

#define SYSMON_2_TEMPERATURE_RSVD_SHIFT                              0
#define SYSMON_2_TEMPERATURE_ADC_SHIFT                               6

/*
 * gain_error
 */

union sysmon_2_gain_error {
  struct {
      uint32_t magnitude                       :  6;   //   [ 5: 0]
      uint32_t sign                            :  1;   //   [    6]
  };
  uint32_t _v;
};

#define SYSMON_2_GAIN_ERROR_MAGNITUDE_MASK                  0x0000003F
#define SYSMON_2_GAIN_ERROR_SIGN_MASK                       0x00000040

#define SYSMON_2_GAIN_ERROR_MAGNITUDE_SHIFT                          0
#define SYSMON_2_GAIN_ERROR_SIGN_SHIFT                               6

#define SYSMON_2_VAUX_COUNT                                 16

/*
 * flag
 */

union sysmon_2_flag {
  struct {
      uint32_t alm0                            :  1;   //   [    0]
      uint32_t alm1                            :  1;   //   [    1]
      uint32_t alm2                            :  1;   //   [    2]
      uint32_t over_temperature                :  1;   //   [    3]
      uint32_t alm3                            :  1;   //   [    4]
      uint32_t alm4                            :  1;   //   [    5]
      uint32_t alm5                            :  1;   //   [    6]
      uint32_t alm6                            :  1;   //   [    7]
      uint32_t rsvd                            :  1;   //   [    8]
      uint32_t ref                             :  1;   //   [    9]
      uint32_t jtgr                            :  1;   //   [   10]
      uint32_t jtgd                            :  1;   //   [   11]
  };
  uint32_t _v;
};

#define SYSMON_2_FLAG_ALM0_MASK                             0x00000001
#define SYSMON_2_FLAG_ALM1_MASK                             0x00000002
#define SYSMON_2_FLAG_ALM2_MASK                             0x00000004
#define SYSMON_2_FLAG_OVER_TEMPERATURE_MASK                 0x00000008
#define SYSMON_2_FLAG_ALM3_MASK                             0x00000010
#define SYSMON_2_FLAG_ALM4_MASK                             0x00000020
#define SYSMON_2_FLAG_ALM5_MASK                             0x00000040
#define SYSMON_2_FLAG_ALM6_MASK                             0x00000080
#define SYSMON_2_FLAG_RSVD_MASK                             0x00000100
#define SYSMON_2_FLAG_REF_MASK                              0x00000200
#define SYSMON_2_FLAG_JTGR_MASK                             0x00000400
#define SYSMON_2_FLAG_JTGD_MASK                             0x00000800

#define SYSMON_2_FLAG_ALM0_SHIFT                                     0
#define SYSMON_2_FLAG_ALM1_SHIFT                                     1
#define SYSMON_2_FLAG_ALM2_SHIFT                                     2
#define SYSMON_2_FLAG_OVER_TEMPERATURE_SHIFT                         3
#define SYSMON_2_FLAG_ALM3_SHIFT                                     4
#define SYSMON_2_FLAG_ALM4_SHIFT                                     5
#define SYSMON_2_FLAG_ALM5_SHIFT                                     6
#define SYSMON_2_FLAG_ALM6_SHIFT                                     7
#define SYSMON_2_FLAG_RSVD_SHIFT                                     8
#define SYSMON_2_FLAG_REF_SHIFT                                      9
#define SYSMON_2_FLAG_JTGR_SHIFT                                    10
#define SYSMON_2_FLAG_JTGD_SHIFT                                    11
enum sysmon_2_flag_ref {
  SYSMON_2_FLAG_REF_EXTERNAL               = 0x0,
  SYSMON_2_FLAG_REF_INTERNAL               = 0x1,
};

/*
 * config_reg_0
 */

union sysmon_2_config_reg_0 {
  struct {
      uint32_t ch                              :  6;   //   [ 5: 0]
      uint32_t rsvd0                           :  2;   //   [ 7: 6]
      uint32_t acq                             :  1;   //   [    8]
      uint32_t ec                              :  1;   //   [    9]
      uint32_t bu                              :  1;   //   [   10]
      uint32_t mux                             :  1;   //   [   11]
      uint32_t avg                             :  2;   //   [13:12]
      uint32_t rsvd1                           :  1;   //   [   14]
      uint32_t cavg                            :  1;   //   [   15]
  };
  uint32_t _v;
};

#define SYSMON_2_CONFIG_REG_0_CH_MASK                       0x0000003F
#define SYSMON_2_CONFIG_REG_0_RSVD0_MASK                    0x000000C0
#define SYSMON_2_CONFIG_REG_0_ACQ_MASK                      0x00000100
#define SYSMON_2_CONFIG_REG_0_EC_MASK                       0x00000200
#define SYSMON_2_CONFIG_REG_0_BU_MASK                       0x00000400
#define SYSMON_2_CONFIG_REG_0_MUX_MASK                      0x00000800
#define SYSMON_2_CONFIG_REG_0_AVG_MASK                      0x00003000
#define SYSMON_2_CONFIG_REG_0_RSVD1_MASK                    0x00004000
#define SYSMON_2_CONFIG_REG_0_CAVG_MASK                     0x00008000

#define SYSMON_2_CONFIG_REG_0_CH_SHIFT                               0
#define SYSMON_2_CONFIG_REG_0_RSVD0_SHIFT                            6
#define SYSMON_2_CONFIG_REG_0_ACQ_SHIFT                              8
#define SYSMON_2_CONFIG_REG_0_EC_SHIFT                               9
#define SYSMON_2_CONFIG_REG_0_BU_SHIFT                              10
#define SYSMON_2_CONFIG_REG_0_MUX_SHIFT                             11
#define SYSMON_2_CONFIG_REG_0_AVG_SHIFT                             12
#define SYSMON_2_CONFIG_REG_0_RSVD1_SHIFT                           14
#define SYSMON_2_CONFIG_REG_0_CAVG_SHIFT                            15
enum sysmon_2_config_reg_0_ch {
  SYSMON_2_CONFIG_REG_0_CH_TEMPERATURE     = 0x0,
  SYSMON_2_CONFIG_REG_0_CH_VCCINT          = 0x1,
  SYSMON_2_CONFIG_REG_0_CH_VCCAUX          = 0x2,
  SYSMON_2_CONFIG_REG_0_CH_VP_VN           = 0x3,
  SYSMON_2_CONFIG_REG_0_CH_VREFP           = 0x4,
  SYSMON_2_CONFIG_REG_0_CH_VREFN           = 0x5,
  SYSMON_2_CONFIG_REG_0_CH_VCCBRAM         = 0x6,
  SYSMON_2_CONFIG_REG_0_CH_CALIBRATION     = 0x8,
  SYSMON_2_CONFIG_REG_0_CH_VCC_PSINTLP     = 0xD,
  SYSMON_2_CONFIG_REG_0_CH_VCC_PSINTFP     = 0xE,
  SYSMON_2_CONFIG_REG_0_CH_VCC_PSAUX       = 0xF,
  SYSMON_2_CONFIG_REG_0_CH_VAUX0           = 0x10,
  SYSMON_2_CONFIG_REG_0_CH_VAUX1           = 0x11,
  SYSMON_2_CONFIG_REG_0_CH_VAUX2           = 0x12,
  SYSMON_2_CONFIG_REG_0_CH_VAUX3           = 0x13,
  SYSMON_2_CONFIG_REG_0_CH_VAUX4           = 0x14,
  SYSMON_2_CONFIG_REG_0_CH_VAUX5           = 0x15,
  SYSMON_2_CONFIG_REG_0_CH_VAUX6           = 0x16,
  SYSMON_2_CONFIG_REG_0_CH_VAUX7           = 0x17,
  SYSMON_2_CONFIG_REG_0_CH_VAUX8           = 0x18,
  SYSMON_2_CONFIG_REG_0_CH_VAUX9           = 0x19,
  SYSMON_2_CONFIG_REG_0_CH_VAUX10          = 0x1A,
  SYSMON_2_CONFIG_REG_0_CH_VAUX11          = 0x1B,
  SYSMON_2_CONFIG_REG_0_CH_VAUX12          = 0x1C,
  SYSMON_2_CONFIG_REG_0_CH_VAUX13          = 0x1D,
  SYSMON_2_CONFIG_REG_0_CH_VAUX14          = 0x1E,
  SYSMON_2_CONFIG_REG_0_CH_VAUX15          = 0x1F,
  SYSMON_2_CONFIG_REG_0_CH_VUSER0          = 0x20,
  SYSMON_2_CONFIG_REG_0_CH_VUSER1          = 0x21,
  SYSMON_2_CONFIG_REG_0_CH_VUSER2          = 0x22,
  SYSMON_2_CONFIG_REG_0_CH_VUSER3          = 0x23,
};
enum sysmon_2_config_reg_0_avg {
  SYSMON_2_CONFIG_REG_0_AVG_NONE           = 0x0,
  SYSMON_2_CONFIG_REG_0_AVG_16_SAMPLES     = 0x1,
  SYSMON_2_CONFIG_REG_0_AVG_64_SAMPLES     = 0x2,
  SYSMON_2_CONFIG_REG_0_AVG_256_SAMPLES    = 0x3,
};

/*
 * config_reg_1
 */

union sysmon_2_config_reg_1 {
  struct {
      uint32_t over_temperature                :  1;   //   [    0]
      uint32_t alm0                            :  1;   //   [    1]
      uint32_t alm1                            :  1;   //   [    2]
      uint32_t alm2                            :  1;   //   [    3]
      uint32_t cal0                            :  1;   //   [    4]
      uint32_t rsvd                            :  1;   //   [    5]
      uint32_t cal2                            :  1;   //   [    6]
      uint32_t cal3                            :  1;   //   [    7]
      uint32_t alm3                            :  1;   //   [    8]
      uint32_t alm4                            :  1;   //   [    9]
      uint32_t alm5                            :  1;   //   [   10]
      uint32_t alm6                            :  1;   //   [   11]
      uint32_t seq                             :  4;   //   [15:12]
  };
  uint32_t _v;
};

#define SYSMON_2_CONFIG_REG_1_OVER_TEMPERATURE_MASK         0x00000001
#define SYSMON_2_CONFIG_REG_1_ALM0_MASK                     0x00000002
#define SYSMON_2_CONFIG_REG_1_ALM1_MASK                     0x00000004
#define SYSMON_2_CONFIG_REG_1_ALM2_MASK                     0x00000008
#define SYSMON_2_CONFIG_REG_1_CAL0_MASK                     0x00000010
#define SYSMON_2_CONFIG_REG_1_RSVD_MASK                     0x00000020
#define SYSMON_2_CONFIG_REG_1_CAL2_MASK                     0x00000040
#define SYSMON_2_CONFIG_REG_1_CAL3_MASK                     0x00000080
#define SYSMON_2_CONFIG_REG_1_ALM3_MASK                     0x00000100
#define SYSMON_2_CONFIG_REG_1_ALM4_MASK                     0x00000200
#define SYSMON_2_CONFIG_REG_1_ALM5_MASK                     0x00000400
#define SYSMON_2_CONFIG_REG_1_ALM6_MASK                     0x00000800
#define SYSMON_2_CONFIG_REG_1_SEQ_MASK                      0x0000F000

#define SYSMON_2_CONFIG_REG_1_OVER_TEMPERATURE_SHIFT                 0
#define SYSMON_2_CONFIG_REG_1_ALM0_SHIFT                             1
#define SYSMON_2_CONFIG_REG_1_ALM1_SHIFT                             2
#define SYSMON_2_CONFIG_REG_1_ALM2_SHIFT                             3
#define SYSMON_2_CONFIG_REG_1_CAL0_SHIFT                             4
#define SYSMON_2_CONFIG_REG_1_RSVD_SHIFT                             5
#define SYSMON_2_CONFIG_REG_1_CAL2_SHIFT                             6
#define SYSMON_2_CONFIG_REG_1_CAL3_SHIFT                             7
#define SYSMON_2_CONFIG_REG_1_ALM3_SHIFT                             8
#define SYSMON_2_CONFIG_REG_1_ALM4_SHIFT                             9
#define SYSMON_2_CONFIG_REG_1_ALM5_SHIFT                            10
#define SYSMON_2_CONFIG_REG_1_ALM6_SHIFT                            11
#define SYSMON_2_CONFIG_REG_1_SEQ_SHIFT                             12
enum sysmon_2_config_reg_1_seq {
  SYSMON_2_CONFIG_REG_1_SEQ_DEFAULT        = 0x0,
  SYSMON_2_CONFIG_REG_1_SEQ_SINGLE_PASS    = 0x1,
  SYSMON_2_CONFIG_REG_1_SEQ_CONTINUOUS     = 0x2,
  SYSMON_2_CONFIG_REG_1_SEQ_SINGLE_CHANNEL = 0x3,
};

/*
 * config_reg_2
 */

union sysmon_2_config_reg_2 {
  struct {
      uint32_t rsvd                            :  8;   //   [ 7: 0]
      uint32_t cd                              :  8;   //   [15: 8]
  };
  uint32_t _v;
};

#define SYSMON_2_CONFIG_REG_2_RSVD_MASK                     0x000000FF
#define SYSMON_2_CONFIG_REG_2_CD_MASK                       0x0000FF00

#define SYSMON_2_CONFIG_REG_2_RSVD_SHIFT                             0
#define SYSMON_2_CONFIG_REG_2_CD_SHIFT                               8

/*
 * config_reg_3
 */

union sysmon_2_config_reg_3 {
  struct {
      uint32_t alm8                            :  1;   //   [    0]
      uint32_t alm9                            :  1;   //   [    1]
      uint32_t alm10                           :  1;   //   [    2]
      uint32_t alm11                           :  1;   //   [    3]
      uint32_t rsvd                            :  3;   //   [ 6: 4]
      uint32_t i2c_en                          :  1;   //   [    7]
      uint32_t i2c_addr                        :  7;   //   [14: 8]
  };
  uint32_t _v;
};

#define SYSMON_2_CONFIG_REG_3_ALM8_MASK                     0x00000001
#define SYSMON_2_CONFIG_REG_3_ALM9_MASK                     0x00000002
#define SYSMON_2_CONFIG_REG_3_ALM10_MASK                    0x00000004
#define SYSMON_2_CONFIG_REG_3_ALM11_MASK                    0x00000008
#define SYSMON_2_CONFIG_REG_3_RSVD_MASK                     0x00000070
#define SYSMON_2_CONFIG_REG_3_I2C_EN_MASK                   0x00000080
#define SYSMON_2_CONFIG_REG_3_I2C_ADDR_MASK                 0x00007F00

#define SYSMON_2_CONFIG_REG_3_ALM8_SHIFT                             0
#define SYSMON_2_CONFIG_REG_3_ALM9_SHIFT                             1
#define SYSMON_2_CONFIG_REG_3_ALM10_SHIFT                            2
#define SYSMON_2_CONFIG_REG_3_ALM11_SHIFT                            3
#define SYSMON_2_CONFIG_REG_3_RSVD_SHIFT                             4
#define SYSMON_2_CONFIG_REG_3_I2C_EN_SHIFT                           7
#define SYSMON_2_CONFIG_REG_3_I2C_ADDR_SHIFT                         8

/*
 * config_reg_4
 */

union sysmon_2_config_reg_4 {
  struct {
      uint32_t pmbus_hrio                      :  4;   //   [ 3: 0]
      uint32_t rsvd0                           :  4;   //   [ 7: 4]
      uint32_t slow_seq                        :  2;   //   [ 9: 8]
      uint32_t slow_eos                        :  2;   //   [11:10]
  };
  uint32_t _v;
};

#define SYSMON_2_CONFIG_REG_4_PMBUS_HRIO_MASK               0x0000000F
#define SYSMON_2_CONFIG_REG_4_RSVD0_MASK                    0x000000F0
#define SYSMON_2_CONFIG_REG_4_SLOW_SEQ_MASK                 0x00000300
#define SYSMON_2_CONFIG_REG_4_SLOW_EOS_MASK                 0x00000C00

#define SYSMON_2_CONFIG_REG_4_PMBUS_HRIO_SHIFT                       0
#define SYSMON_2_CONFIG_REG_4_RSVD0_SHIFT                            4
#define SYSMON_2_CONFIG_REG_4_SLOW_SEQ_SHIFT                         8
#define SYSMON_2_CONFIG_REG_4_SLOW_EOS_SHIFT                        10
enum sysmon_2_config_reg_4_slow_seq {
  SYSMON_2_CONFIG_REG_4_SLOW_SEQ_EVERY     = 0x0,
  SYSMON_2_CONFIG_REG_4_SLOW_SEQ_EVERY_4TH = 0x1,
  SYSMON_2_CONFIG_REG_4_SLOW_SEQ_EVERY_16TH = 0x2,
  SYSMON_2_CONFIG_REG_4_SLOW_SEQ_EVERY_64TH = 0x3,
};
enum sysmon_2_config_reg_4_slow_eos {
  SYSMON_2_CONFIG_REG_4_SLOW_EOS_FROM_SEQCHSEL = 0x0,
  SYSMON_2_CONFIG_REG_4_SLOW_EOS_FROM_SLOWCHSEL = 0x1,
  SYSMON_2_CONFIG_REG_4_SLOW_EOS_FROM_SEQCHSEL_AND_SLOWCHSEL = 0x2,
  SYSMON_2_CONFIG_REG_4_SLOW_EOS_DEFAULT   = 0x3,
};

/*
 * analog_bus
 */

union sysmon_2_analog_bus {
  struct {
      uint32_t vuser0                          :  4;   //   [ 3: 0]
      uint32_t vuser1                          :  4;   //   [ 7: 4]
      uint32_t vuser2                          :  4;   //   [11: 8]
      uint32_t vuser3                          :  4;   //   [15:12]
  };
  uint32_t _v;
};

#define SYSMON_2_ANALOG_BUS_VUSER0_MASK                     0x0000000F
#define SYSMON_2_ANALOG_BUS_VUSER1_MASK                     0x000000F0
#define SYSMON_2_ANALOG_BUS_VUSER2_MASK                     0x00000F00
#define SYSMON_2_ANALOG_BUS_VUSER3_MASK                     0x0000F000

#define SYSMON_2_ANALOG_BUS_VUSER0_SHIFT                             0
#define SYSMON_2_ANALOG_BUS_VUSER1_SHIFT                             4
#define SYSMON_2_ANALOG_BUS_VUSER2_SHIFT                             8
#define SYSMON_2_ANALOG_BUS_VUSER3_SHIFT                            12

/*
 * seqchsel0
 */

union sysmon_2_seqchsel0 {
  struct {
      uint32_t vuser0                          :  1;   //   [    0]
      uint32_t vuser1                          :  1;   //   [    1]
      uint32_t vuser2                          :  1;   //   [    2]
      uint32_t vuser3                          :  1;   //   [    3]
  };
  uint32_t _v;
};

#define SYSMON_2_SEQCHSEL0_VUSER0_MASK                      0x00000001
#define SYSMON_2_SEQCHSEL0_VUSER1_MASK                      0x00000002
#define SYSMON_2_SEQCHSEL0_VUSER2_MASK                      0x00000004
#define SYSMON_2_SEQCHSEL0_VUSER3_MASK                      0x00000008

#define SYSMON_2_SEQCHSEL0_VUSER0_SHIFT                              0
#define SYSMON_2_SEQCHSEL0_VUSER1_SHIFT                              1
#define SYSMON_2_SEQCHSEL0_VUSER2_SHIFT                              2
#define SYSMON_2_SEQCHSEL0_VUSER3_SHIFT                              3

/*
 * seqavg0
 */

union sysmon_2_seqavg0 {
  struct {
      uint32_t vuser0                          :  1;   //   [    0]
      uint32_t vuser1                          :  1;   //   [    1]
      uint32_t vuser2                          :  1;   //   [    2]
      uint32_t vuser3                          :  1;   //   [    3]
  };
  uint32_t _v;
};

#define SYSMON_2_SEQAVG0_VUSER0_MASK                        0x00000001
#define SYSMON_2_SEQAVG0_VUSER1_MASK                        0x00000002
#define SYSMON_2_SEQAVG0_VUSER2_MASK                        0x00000004
#define SYSMON_2_SEQAVG0_VUSER3_MASK                        0x00000008

#define SYSMON_2_SEQAVG0_VUSER0_SHIFT                                0
#define SYSMON_2_SEQAVG0_VUSER1_SHIFT                                1
#define SYSMON_2_SEQAVG0_VUSER2_SHIFT                                2
#define SYSMON_2_SEQAVG0_VUSER3_SHIFT                                3

/*
 * seqchsel1
 */

union sysmon_2_seqchsel1 {
  struct {
      uint32_t cal_enable                      :  1;   //   [    0]
      uint32_t rsvd                            :  4;   //   [ 4: 1]
      uint32_t vcc_psintlp                     :  1;   //   [    5]
      uint32_t vcc_psintfp                     :  1;   //   [    6]
      uint32_t vcc_psaux                       :  1;   //   [    7]
      uint32_t temperature                     :  1;   //   [    8]
      uint32_t vccint                          :  1;   //   [    9]
      uint32_t vccaux                          :  1;   //   [   10]
      uint32_t vp_vn                           :  1;   //   [   11]
      uint32_t vrefp                           :  1;   //   [   12]
      uint32_t vrefn                           :  1;   //   [   13]
      uint32_t vccbram                         :  1;   //   [   14]
  };
  uint32_t _v;
};

#define SYSMON_2_SEQCHSEL1_CAL_ENABLE_MASK                  0x00000001
#define SYSMON_2_SEQCHSEL1_RSVD_MASK                        0x0000001E
#define SYSMON_2_SEQCHSEL1_VCC_PSINTLP_MASK                 0x00000020
#define SYSMON_2_SEQCHSEL1_VCC_PSINTFP_MASK                 0x00000040
#define SYSMON_2_SEQCHSEL1_VCC_PSAUX_MASK                   0x00000080
#define SYSMON_2_SEQCHSEL1_TEMPERATURE_MASK                 0x00000100
#define SYSMON_2_SEQCHSEL1_VCCINT_MASK                      0x00000200
#define SYSMON_2_SEQCHSEL1_VCCAUX_MASK                      0x00000400
#define SYSMON_2_SEQCHSEL1_VP_VN_MASK                       0x00000800
#define SYSMON_2_SEQCHSEL1_VREFP_MASK                       0x00001000
#define SYSMON_2_SEQCHSEL1_VREFN_MASK                       0x00002000
#define SYSMON_2_SEQCHSEL1_VCCBRAM_MASK                     0x00004000

#define SYSMON_2_SEQCHSEL1_CAL_ENABLE_SHIFT                          0
#define SYSMON_2_SEQCHSEL1_RSVD_SHIFT                                1
#define SYSMON_2_SEQCHSEL1_VCC_PSINTLP_SHIFT                         5
#define SYSMON_2_SEQCHSEL1_VCC_PSINTFP_SHIFT                         6
#define SYSMON_2_SEQCHSEL1_VCC_PSAUX_SHIFT                           7
#define SYSMON_2_SEQCHSEL1_TEMPERATURE_SHIFT                         8
#define SYSMON_2_SEQCHSEL1_VCCINT_SHIFT                              9
#define SYSMON_2_SEQCHSEL1_VCCAUX_SHIFT                             10
#define SYSMON_2_SEQCHSEL1_VP_VN_SHIFT                              11
#define SYSMON_2_SEQCHSEL1_VREFP_SHIFT                              12
#define SYSMON_2_SEQCHSEL1_VREFN_SHIFT                              13
#define SYSMON_2_SEQCHSEL1_VCCBRAM_SHIFT                            14

/*
 * seqchsel2
 */

union sysmon_2_seqchsel2 {
  struct {
      uint32_t vaux0                           :  1;   //   [    0]
      uint32_t vaux1                           :  1;   //   [    1]
      uint32_t vaux2                           :  1;   //   [    2]
      uint32_t vaux3                           :  1;   //   [    3]
      uint32_t vaux4                           :  1;   //   [    4]
      uint32_t vaux5                           :  1;   //   [    5]
      uint32_t vaux6                           :  1;   //   [    6]
      uint32_t vaux7                           :  1;   //   [    7]
      uint32_t vaux8                           :  1;   //   [    8]
      uint32_t vaux9                           :  1;   //   [    9]
      uint32_t vaux10                          :  1;   //   [   10]
      uint32_t vaux11                          :  1;   //   [   11]
      uint32_t vaux12                          :  1;   //   [   12]
      uint32_t vaux13                          :  1;   //   [   13]
      uint32_t vaux14                          :  1;   //   [   14]
      uint32_t vaux15                          :  1;   //   [   15]
  };
  uint32_t _v;
};

#define SYSMON_2_SEQCHSEL2_VAUX0_MASK                       0x00000001
#define SYSMON_2_SEQCHSEL2_VAUX1_MASK                       0x00000002
#define SYSMON_2_SEQCHSEL2_VAUX2_MASK                       0x00000004
#define SYSMON_2_SEQCHSEL2_VAUX3_MASK                       0x00000008
#define SYSMON_2_SEQCHSEL2_VAUX4_MASK                       0x00000010
#define SYSMON_2_SEQCHSEL2_VAUX5_MASK                       0x00000020
#define SYSMON_2_SEQCHSEL2_VAUX6_MASK                       0x00000040
#define SYSMON_2_SEQCHSEL2_VAUX7_MASK                       0x00000080
#define SYSMON_2_SEQCHSEL2_VAUX8_MASK                       0x00000100
#define SYSMON_2_SEQCHSEL2_VAUX9_MASK                       0x00000200
#define SYSMON_2_SEQCHSEL2_VAUX10_MASK                      0x00000400
#define SYSMON_2_SEQCHSEL2_VAUX11_MASK                      0x00000800
#define SYSMON_2_SEQCHSEL2_VAUX12_MASK                      0x00001000
#define SYSMON_2_SEQCHSEL2_VAUX13_MASK                      0x00002000
#define SYSMON_2_SEQCHSEL2_VAUX14_MASK                      0x00004000
#define SYSMON_2_SEQCHSEL2_VAUX15_MASK                      0x00008000

#define SYSMON_2_SEQCHSEL2_VAUX0_SHIFT                               0
#define SYSMON_2_SEQCHSEL2_VAUX1_SHIFT                               1
#define SYSMON_2_SEQCHSEL2_VAUX2_SHIFT                               2
#define SYSMON_2_SEQCHSEL2_VAUX3_SHIFT                               3
#define SYSMON_2_SEQCHSEL2_VAUX4_SHIFT                               4
#define SYSMON_2_SEQCHSEL2_VAUX5_SHIFT                               5
#define SYSMON_2_SEQCHSEL2_VAUX6_SHIFT                               6
#define SYSMON_2_SEQCHSEL2_VAUX7_SHIFT                               7
#define SYSMON_2_SEQCHSEL2_VAUX8_SHIFT                               8
#define SYSMON_2_SEQCHSEL2_VAUX9_SHIFT                               9
#define SYSMON_2_SEQCHSEL2_VAUX10_SHIFT                             10
#define SYSMON_2_SEQCHSEL2_VAUX11_SHIFT                             11
#define SYSMON_2_SEQCHSEL2_VAUX12_SHIFT                             12
#define SYSMON_2_SEQCHSEL2_VAUX13_SHIFT                             13
#define SYSMON_2_SEQCHSEL2_VAUX14_SHIFT                             14
#define SYSMON_2_SEQCHSEL2_VAUX15_SHIFT                             15

/*
 * seqavg1
 */

union sysmon_2_seqavg1 {
  struct {
      uint32_t rsvd0                           :  5;   //   [ 4: 0]
      uint32_t vcc_psintlp                     :  1;   //   [    5]
      uint32_t vcc_psintfp                     :  1;   //   [    6]
      uint32_t vcc_psaux                       :  1;   //   [    7]
      uint32_t temperature                     :  1;   //   [    8]
      uint32_t vccint                          :  1;   //   [    9]
      uint32_t vccaux                          :  1;   //   [   10]
      uint32_t vp_vn                           :  1;   //   [   11]
      uint32_t rsvd1                           :  2;   //   [13:12]
      uint32_t vccbram                         :  1;   //   [   14]
  };
  uint32_t _v;
};

#define SYSMON_2_SEQAVG1_RSVD0_MASK                         0x0000001F
#define SYSMON_2_SEQAVG1_VCC_PSINTLP_MASK                   0x00000020
#define SYSMON_2_SEQAVG1_VCC_PSINTFP_MASK                   0x00000040
#define SYSMON_2_SEQAVG1_VCC_PSAUX_MASK                     0x00000080
#define SYSMON_2_SEQAVG1_TEMPERATURE_MASK                   0x00000100
#define SYSMON_2_SEQAVG1_VCCINT_MASK                        0x00000200
#define SYSMON_2_SEQAVG1_VCCAUX_MASK                        0x00000400
#define SYSMON_2_SEQAVG1_VP_VN_MASK                         0x00000800
#define SYSMON_2_SEQAVG1_RSVD1_MASK                         0x00003000
#define SYSMON_2_SEQAVG1_VCCBRAM_MASK                       0x00004000

#define SYSMON_2_SEQAVG1_RSVD0_SHIFT                                 0
#define SYSMON_2_SEQAVG1_VCC_PSINTLP_SHIFT                           5
#define SYSMON_2_SEQAVG1_VCC_PSINTFP_SHIFT                           6
#define SYSMON_2_SEQAVG1_VCC_PSAUX_SHIFT                             7
#define SYSMON_2_SEQAVG1_TEMPERATURE_SHIFT                           8
#define SYSMON_2_SEQAVG1_VCCINT_SHIFT                                9
#define SYSMON_2_SEQAVG1_VCCAUX_SHIFT                               10
#define SYSMON_2_SEQAVG1_VP_VN_SHIFT                                11
#define SYSMON_2_SEQAVG1_RSVD1_SHIFT                                12
#define SYSMON_2_SEQAVG1_VCCBRAM_SHIFT                              14

/*
 * seqavg2
 */

union sysmon_2_seqavg2 {
  struct {
      uint32_t vaux0                           :  1;   //   [    0]
      uint32_t vaux1                           :  1;   //   [    1]
      uint32_t vaux2                           :  1;   //   [    2]
      uint32_t vaux3                           :  1;   //   [    3]
      uint32_t vaux4                           :  1;   //   [    4]
      uint32_t vaux5                           :  1;   //   [    5]
      uint32_t vaux6                           :  1;   //   [    6]
      uint32_t vaux7                           :  1;   //   [    7]
      uint32_t vaux8                           :  1;   //   [    8]
      uint32_t vaux9                           :  1;   //   [    9]
      uint32_t vaux10                          :  1;   //   [   10]
      uint32_t vaux11                          :  1;   //   [   11]
      uint32_t vaux12                          :  1;   //   [   12]
      uint32_t vaux13                          :  1;   //   [   13]
      uint32_t vaux14                          :  1;   //   [   14]
      uint32_t vaux15                          :  1;   //   [   15]
  };
  uint32_t _v;
};

#define SYSMON_2_SEQAVG2_VAUX0_MASK                         0x00000001
#define SYSMON_2_SEQAVG2_VAUX1_MASK                         0x00000002
#define SYSMON_2_SEQAVG2_VAUX2_MASK                         0x00000004
#define SYSMON_2_SEQAVG2_VAUX3_MASK                         0x00000008
#define SYSMON_2_SEQAVG2_VAUX4_MASK                         0x00000010
#define SYSMON_2_SEQAVG2_VAUX5_MASK                         0x00000020
#define SYSMON_2_SEQAVG2_VAUX6_MASK                         0x00000040
#define SYSMON_2_SEQAVG2_VAUX7_MASK                         0x00000080
#define SYSMON_2_SEQAVG2_VAUX8_MASK                         0x00000100
#define SYSMON_2_SEQAVG2_VAUX9_MASK                         0x00000200
#define SYSMON_2_SEQAVG2_VAUX10_MASK                        0x00000400
#define SYSMON_2_SEQAVG2_VAUX11_MASK                        0x00000800
#define SYSMON_2_SEQAVG2_VAUX12_MASK                        0x00001000
#define SYSMON_2_SEQAVG2_VAUX13_MASK                        0x00002000
#define SYSMON_2_SEQAVG2_VAUX14_MASK                        0x00004000
#define SYSMON_2_SEQAVG2_VAUX15_MASK                        0x00008000

#define SYSMON_2_SEQAVG2_VAUX0_SHIFT                                 0
#define SYSMON_2_SEQAVG2_VAUX1_SHIFT                                 1
#define SYSMON_2_SEQAVG2_VAUX2_SHIFT                                 2
#define SYSMON_2_SEQAVG2_VAUX3_SHIFT                                 3
#define SYSMON_2_SEQAVG2_VAUX4_SHIFT                                 4
#define SYSMON_2_SEQAVG2_VAUX5_SHIFT                                 5
#define SYSMON_2_SEQAVG2_VAUX6_SHIFT                                 6
#define SYSMON_2_SEQAVG2_VAUX7_SHIFT                                 7
#define SYSMON_2_SEQAVG2_VAUX8_SHIFT                                 8
#define SYSMON_2_SEQAVG2_VAUX9_SHIFT                                 9
#define SYSMON_2_SEQAVG2_VAUX10_SHIFT                               10
#define SYSMON_2_SEQAVG2_VAUX11_SHIFT                               11
#define SYSMON_2_SEQAVG2_VAUX12_SHIFT                               12
#define SYSMON_2_SEQAVG2_VAUX13_SHIFT                               13
#define SYSMON_2_SEQAVG2_VAUX14_SHIFT                               14
#define SYSMON_2_SEQAVG2_VAUX15_SHIFT                               15

/*
 * seqinmode0
 */

union sysmon_2_seqinmode0 {
  struct {
      uint32_t rsvd                            : 11;   //   [10: 0]
      uint32_t vp_vn                           :  1;   //   [   11]
  };
  uint32_t _v;
};

#define SYSMON_2_SEQINMODE0_RSVD_MASK                       0x000007FF
#define SYSMON_2_SEQINMODE0_VP_VN_MASK                      0x00000800

#define SYSMON_2_SEQINMODE0_RSVD_SHIFT                               0
#define SYSMON_2_SEQINMODE0_VP_VN_SHIFT                             11

/*
 * seqinmode1
 */

union sysmon_2_seqinmode1 {
  struct {
      uint32_t vaux0                           :  1;   //   [    0]
      uint32_t vaux1                           :  1;   //   [    1]
      uint32_t vaux2                           :  1;   //   [    2]
      uint32_t vaux3                           :  1;   //   [    3]
      uint32_t vaux4                           :  1;   //   [    4]
      uint32_t vaux5                           :  1;   //   [    5]
      uint32_t vaux6                           :  1;   //   [    6]
      uint32_t vaux7                           :  1;   //   [    7]
      uint32_t vaux8                           :  1;   //   [    8]
      uint32_t vaux9                           :  1;   //   [    9]
      uint32_t vaux10                          :  1;   //   [   10]
      uint32_t vaux11                          :  1;   //   [   11]
      uint32_t vaux12                          :  1;   //   [   12]
      uint32_t vaux13                          :  1;   //   [   13]
      uint32_t vaux14                          :  1;   //   [   14]
      uint32_t vaux15                          :  1;   //   [   15]
  };
  uint32_t _v;
};

#define SYSMON_2_SEQINMODE1_VAUX0_MASK                      0x00000001
#define SYSMON_2_SEQINMODE1_VAUX1_MASK                      0x00000002
#define SYSMON_2_SEQINMODE1_VAUX2_MASK                      0x00000004
#define SYSMON_2_SEQINMODE1_VAUX3_MASK                      0x00000008
#define SYSMON_2_SEQINMODE1_VAUX4_MASK                      0x00000010
#define SYSMON_2_SEQINMODE1_VAUX5_MASK                      0x00000020
#define SYSMON_2_SEQINMODE1_VAUX6_MASK                      0x00000040
#define SYSMON_2_SEQINMODE1_VAUX7_MASK                      0x00000080
#define SYSMON_2_SEQINMODE1_VAUX8_MASK                      0x00000100
#define SYSMON_2_SEQINMODE1_VAUX9_MASK                      0x00000200
#define SYSMON_2_SEQINMODE1_VAUX10_MASK                     0x00000400
#define SYSMON_2_SEQINMODE1_VAUX11_MASK                     0x00000800
#define SYSMON_2_SEQINMODE1_VAUX12_MASK                     0x00001000
#define SYSMON_2_SEQINMODE1_VAUX13_MASK                     0x00002000
#define SYSMON_2_SEQINMODE1_VAUX14_MASK                     0x00004000
#define SYSMON_2_SEQINMODE1_VAUX15_MASK                     0x00008000

#define SYSMON_2_SEQINMODE1_VAUX0_SHIFT                              0
#define SYSMON_2_SEQINMODE1_VAUX1_SHIFT                              1
#define SYSMON_2_SEQINMODE1_VAUX2_SHIFT                              2
#define SYSMON_2_SEQINMODE1_VAUX3_SHIFT                              3
#define SYSMON_2_SEQINMODE1_VAUX4_SHIFT                              4
#define SYSMON_2_SEQINMODE1_VAUX5_SHIFT                              5
#define SYSMON_2_SEQINMODE1_VAUX6_SHIFT                              6
#define SYSMON_2_SEQINMODE1_VAUX7_SHIFT                              7
#define SYSMON_2_SEQINMODE1_VAUX8_SHIFT                              8
#define SYSMON_2_SEQINMODE1_VAUX9_SHIFT                              9
#define SYSMON_2_SEQINMODE1_VAUX10_SHIFT                            10
#define SYSMON_2_SEQINMODE1_VAUX11_SHIFT                            11
#define SYSMON_2_SEQINMODE1_VAUX12_SHIFT                            12
#define SYSMON_2_SEQINMODE1_VAUX13_SHIFT                            13
#define SYSMON_2_SEQINMODE1_VAUX14_SHIFT                            14
#define SYSMON_2_SEQINMODE1_VAUX15_SHIFT                            15

/*
 * seqacq0
 */

union sysmon_2_seqacq0 {
  struct {
      uint32_t rsvd                            : 11;   //   [10: 0]
      uint32_t vp_vn                           :  1;   //   [   11]
  };
  uint32_t _v;
};

#define SYSMON_2_SEQACQ0_RSVD_MASK                          0x000007FF
#define SYSMON_2_SEQACQ0_VP_VN_MASK                         0x00000800

#define SYSMON_2_SEQACQ0_RSVD_SHIFT                                  0
#define SYSMON_2_SEQACQ0_VP_VN_SHIFT                                11

/*
 * seqacq1
 */

union sysmon_2_seqacq1 {
  struct {
      uint32_t vaux0                           :  1;   //   [    0]
      uint32_t vaux1                           :  1;   //   [    1]
      uint32_t vaux2                           :  1;   //   [    2]
      uint32_t vaux3                           :  1;   //   [    3]
      uint32_t vaux4                           :  1;   //   [    4]
      uint32_t vaux5                           :  1;   //   [    5]
      uint32_t vaux6                           :  1;   //   [    6]
      uint32_t vaux7                           :  1;   //   [    7]
      uint32_t vaux8                           :  1;   //   [    8]
      uint32_t vaux9                           :  1;   //   [    9]
      uint32_t vaux10                          :  1;   //   [   10]
      uint32_t vaux11                          :  1;   //   [   11]
      uint32_t vaux12                          :  1;   //   [   12]
      uint32_t vaux13                          :  1;   //   [   13]
      uint32_t vaux14                          :  1;   //   [   14]
      uint32_t vaux15                          :  1;   //   [   15]
  };
  uint32_t _v;
};

#define SYSMON_2_SEQACQ1_VAUX0_MASK                         0x00000001
#define SYSMON_2_SEQACQ1_VAUX1_MASK                         0x00000002
#define SYSMON_2_SEQACQ1_VAUX2_MASK                         0x00000004
#define SYSMON_2_SEQACQ1_VAUX3_MASK                         0x00000008
#define SYSMON_2_SEQACQ1_VAUX4_MASK                         0x00000010
#define SYSMON_2_SEQACQ1_VAUX5_MASK                         0x00000020
#define SYSMON_2_SEQACQ1_VAUX6_MASK                         0x00000040
#define SYSMON_2_SEQACQ1_VAUX7_MASK                         0x00000080
#define SYSMON_2_SEQACQ1_VAUX8_MASK                         0x00000100
#define SYSMON_2_SEQACQ1_VAUX9_MASK                         0x00000200
#define SYSMON_2_SEQACQ1_VAUX10_MASK                        0x00000400
#define SYSMON_2_SEQACQ1_VAUX11_MASK                        0x00000800
#define SYSMON_2_SEQACQ1_VAUX12_MASK                        0x00001000
#define SYSMON_2_SEQACQ1_VAUX13_MASK                        0x00002000
#define SYSMON_2_SEQACQ1_VAUX14_MASK                        0x00004000
#define SYSMON_2_SEQACQ1_VAUX15_MASK                        0x00008000

#define SYSMON_2_SEQACQ1_VAUX0_SHIFT                                 0
#define SYSMON_2_SEQACQ1_VAUX1_SHIFT                                 1
#define SYSMON_2_SEQACQ1_VAUX2_SHIFT                                 2
#define SYSMON_2_SEQACQ1_VAUX3_SHIFT                                 3
#define SYSMON_2_SEQACQ1_VAUX4_SHIFT                                 4
#define SYSMON_2_SEQACQ1_VAUX5_SHIFT                                 5
#define SYSMON_2_SEQACQ1_VAUX6_SHIFT                                 6
#define SYSMON_2_SEQACQ1_VAUX7_SHIFT                                 7
#define SYSMON_2_SEQACQ1_VAUX8_SHIFT                                 8
#define SYSMON_2_SEQACQ1_VAUX9_SHIFT                                 9
#define SYSMON_2_SEQACQ1_VAUX10_SHIFT                               10
#define SYSMON_2_SEQACQ1_VAUX11_SHIFT                               11
#define SYSMON_2_SEQACQ1_VAUX12_SHIFT                               12
#define SYSMON_2_SEQACQ1_VAUX13_SHIFT                               13
#define SYSMON_2_SEQACQ1_VAUX14_SHIFT                               14
#define SYSMON_2_SEQACQ1_VAUX15_SHIFT                               15

/*
 * slowchsel0
 */

union sysmon_2_slowchsel0 {
  struct {
      uint32_t slow_enable                     :  1;   //   [    0]
      uint32_t rsvd                            :  4;   //   [ 4: 1]
      uint32_t vcc_psintlp                     :  1;   //   [    5]
      uint32_t vcc_psintfp                     :  1;   //   [    6]
      uint32_t vcc_psaux                       :  1;   //   [    7]
      uint32_t temperature                     :  1;   //   [    8]
      uint32_t vccint                          :  1;   //   [    9]
      uint32_t vccaux                          :  1;   //   [   10]
      uint32_t vp_vn                           :  1;   //   [   11]
      uint32_t vrefp                           :  1;   //   [   12]
      uint32_t vrefn                           :  1;   //   [   13]
      uint32_t vccbram                         :  1;   //   [   14]
  };
  uint32_t _v;
};

#define SYSMON_2_SLOWCHSEL0_SLOW_ENABLE_MASK                0x00000001
#define SYSMON_2_SLOWCHSEL0_RSVD_MASK                       0x0000001E
#define SYSMON_2_SLOWCHSEL0_VCC_PSINTLP_MASK                0x00000020
#define SYSMON_2_SLOWCHSEL0_VCC_PSINTFP_MASK                0x00000040
#define SYSMON_2_SLOWCHSEL0_VCC_PSAUX_MASK                  0x00000080
#define SYSMON_2_SLOWCHSEL0_TEMPERATURE_MASK                0x00000100
#define SYSMON_2_SLOWCHSEL0_VCCINT_MASK                     0x00000200
#define SYSMON_2_SLOWCHSEL0_VCCAUX_MASK                     0x00000400
#define SYSMON_2_SLOWCHSEL0_VP_VN_MASK                      0x00000800
#define SYSMON_2_SLOWCHSEL0_VREFP_MASK                      0x00001000
#define SYSMON_2_SLOWCHSEL0_VREFN_MASK                      0x00002000
#define SYSMON_2_SLOWCHSEL0_VCCBRAM_MASK                    0x00004000

#define SYSMON_2_SLOWCHSEL0_SLOW_ENABLE_SHIFT                        0
#define SYSMON_2_SLOWCHSEL0_RSVD_SHIFT                               1
#define SYSMON_2_SLOWCHSEL0_VCC_PSINTLP_SHIFT                        5
#define SYSMON_2_SLOWCHSEL0_VCC_PSINTFP_SHIFT                        6
#define SYSMON_2_SLOWCHSEL0_VCC_PSAUX_SHIFT                          7
#define SYSMON_2_SLOWCHSEL0_TEMPERATURE_SHIFT                        8
#define SYSMON_2_SLOWCHSEL0_VCCINT_SHIFT                             9
#define SYSMON_2_SLOWCHSEL0_VCCAUX_SHIFT                            10
#define SYSMON_2_SLOWCHSEL0_VP_VN_SHIFT                             11
#define SYSMON_2_SLOWCHSEL0_VREFP_SHIFT                             12
#define SYSMON_2_SLOWCHSEL0_VREFN_SHIFT                             13
#define SYSMON_2_SLOWCHSEL0_VCCBRAM_SHIFT                           14

/*
 * slowchsel1
 */

union sysmon_2_slowchsel1 {
  struct {
      uint32_t vaux0                           :  1;   //   [    0]
      uint32_t vaux1                           :  1;   //   [    1]
      uint32_t vaux2                           :  1;   //   [    2]
      uint32_t vaux3                           :  1;   //   [    3]
      uint32_t vaux4                           :  1;   //   [    4]
      uint32_t vaux5                           :  1;   //   [    5]
      uint32_t vaux6                           :  1;   //   [    6]
      uint32_t vaux7                           :  1;   //   [    7]
      uint32_t vaux8                           :  1;   //   [    8]
      uint32_t vaux9                           :  1;   //   [    9]
      uint32_t vaux10                          :  1;   //   [   10]
      uint32_t vaux11                          :  1;   //   [   11]
      uint32_t vaux12                          :  1;   //   [   12]
      uint32_t vaux13                          :  1;   //   [   13]
      uint32_t vaux14                          :  1;   //   [   14]
      uint32_t vaux15                          :  1;   //   [   15]
  };
  uint32_t _v;
};

#define SYSMON_2_SLOWCHSEL1_VAUX0_MASK                      0x00000001
#define SYSMON_2_SLOWCHSEL1_VAUX1_MASK                      0x00000002
#define SYSMON_2_SLOWCHSEL1_VAUX2_MASK                      0x00000004
#define SYSMON_2_SLOWCHSEL1_VAUX3_MASK                      0x00000008
#define SYSMON_2_SLOWCHSEL1_VAUX4_MASK                      0x00000010
#define SYSMON_2_SLOWCHSEL1_VAUX5_MASK                      0x00000020
#define SYSMON_2_SLOWCHSEL1_VAUX6_MASK                      0x00000040
#define SYSMON_2_SLOWCHSEL1_VAUX7_MASK                      0x00000080
#define SYSMON_2_SLOWCHSEL1_VAUX8_MASK                      0x00000100
#define SYSMON_2_SLOWCHSEL1_VAUX9_MASK                      0x00000200
#define SYSMON_2_SLOWCHSEL1_VAUX10_MASK                     0x00000400
#define SYSMON_2_SLOWCHSEL1_VAUX11_MASK                     0x00000800
#define SYSMON_2_SLOWCHSEL1_VAUX12_MASK                     0x00001000
#define SYSMON_2_SLOWCHSEL1_VAUX13_MASK                     0x00002000
#define SYSMON_2_SLOWCHSEL1_VAUX14_MASK                     0x00004000
#define SYSMON_2_SLOWCHSEL1_VAUX15_MASK                     0x00008000

#define SYSMON_2_SLOWCHSEL1_VAUX0_SHIFT                              0
#define SYSMON_2_SLOWCHSEL1_VAUX1_SHIFT                              1
#define SYSMON_2_SLOWCHSEL1_VAUX2_SHIFT                              2
#define SYSMON_2_SLOWCHSEL1_VAUX3_SHIFT                              3
#define SYSMON_2_SLOWCHSEL1_VAUX4_SHIFT                              4
#define SYSMON_2_SLOWCHSEL1_VAUX5_SHIFT                              5
#define SYSMON_2_SLOWCHSEL1_VAUX6_SHIFT                              6
#define SYSMON_2_SLOWCHSEL1_VAUX7_SHIFT                              7
#define SYSMON_2_SLOWCHSEL1_VAUX8_SHIFT                              8
#define SYSMON_2_SLOWCHSEL1_VAUX9_SHIFT                              9
#define SYSMON_2_SLOWCHSEL1_VAUX10_SHIFT                            10
#define SYSMON_2_SLOWCHSEL1_VAUX11_SHIFT                            11
#define SYSMON_2_SLOWCHSEL1_VAUX12_SHIFT                            12
#define SYSMON_2_SLOWCHSEL1_VAUX13_SHIFT                            13
#define SYSMON_2_SLOWCHSEL1_VAUX14_SHIFT                            14
#define SYSMON_2_SLOWCHSEL1_VAUX15_SHIFT                            15

/*
 * slowchsel2
 */

union sysmon_2_slowchsel2 {
  struct {
      uint32_t vuser0                          :  1;   //   [    0]
      uint32_t vuser1                          :  1;   //   [    1]
      uint32_t vuser2                          :  1;   //   [    2]
      uint32_t vuser3                          :  1;   //   [    3]
  };
  uint32_t _v;
};

#define SYSMON_2_SLOWCHSEL2_VUSER0_MASK                     0x00000001
#define SYSMON_2_SLOWCHSEL2_VUSER1_MASK                     0x00000002
#define SYSMON_2_SLOWCHSEL2_VUSER2_MASK                     0x00000004
#define SYSMON_2_SLOWCHSEL2_VUSER3_MASK                     0x00000008

#define SYSMON_2_SLOWCHSEL2_VUSER0_SHIFT                             0
#define SYSMON_2_SLOWCHSEL2_VUSER1_SHIFT                             1
#define SYSMON_2_SLOWCHSEL2_VUSER2_SHIFT                             2
#define SYSMON_2_SLOWCHSEL2_VUSER3_SHIFT                             3


struct sysmon_2_block {
  uint32_t software_reset;                                     // 0x00000000 
  union sysmon_2_status status;                                // 0x00000004 
  union sysmon_2_alarm_output_status alarm_output_status;      // 0x00000008 
  union sysmon_2_convst convst;                                // 0x0000000C 
  union sysmon_2_sysmon_reset sysmon_reset;                    // 0x00000010 
  uint8_t  anon000[72];                                        //
  union sysmon_2_global_interrupt_enable global_interrupt_enable; // 0x0000005C 
  union sysmon_2_ip_interrupt_status ip_interrupt_status;      // 0x00000060 
  uint8_t  anon001[4];                                         //
  union sysmon_2_ip_interrupt_enable ip_interrupt_enable;      // 0x00000068 
  uint8_t  anon002[916];                                       //
  union sysmon_2_temperature temperature;                      // 0x00000400 
  uint32_t vccint;                                             // 0x00000404 
  uint32_t vccaux;                                             // 0x00000408 
  uint32_t vp_vn;                                              // 0x0000040C 
  uint32_t vrefp;                                              // 0x00000410 
  uint32_t vrefn;                                              // 0x00000414 
  uint32_t vccbram;                                            // 0x00000418 
  uint8_t  anon003[4];                                         //
  uint32_t supply_unipolar_offset;                             // 0x00000420 
  uint32_t supply_bipolar_offset;                              // 0x00000424 
  union sysmon_2_gain_error gain_error;                        // 0x00000428 
  uint8_t  anon004[8];                                         //
  uint32_t vcc_psintlp;                                        // 0x00000434 
  uint32_t vcc_psintfp;                                        // 0x00000438 
  uint32_t vcc_psaux;                                          // 0x0000043C 
  uint32_t vaux[16];                                           // 0x00000440 
  uint32_t max_temperature;                                    // 0x00000480 
  uint32_t max_vccint;                                         // 0x00000484 
  uint32_t max_vccaux;                                         // 0x00000488 
  uint32_t max_vccbram;                                        // 0x0000048C 
  uint32_t min_temperature;                                    // 0x00000490 
  uint32_t min_vccint;                                         // 0x00000494 
  uint32_t min_vccaux;                                         // 0x00000498 
  uint32_t min_vccbram;                                        // 0x0000049C 
  uint32_t max_vcc_psintlp;                                    // 0x000004A0 
  uint32_t max_vcc_psintfp;                                    // 0x000004A4 
  uint32_t max_vcc_psaux;                                      // 0x000004A8 
  uint8_t  anon005[4];                                         //
  uint32_t min_vcc_psintlp;                                    // 0x000004B0 
  uint32_t min_vcc_psintfp;                                    // 0x000004B4 
  uint32_t min_vcc_psaux;                                      // 0x000004B8 
  uint8_t  anon006[36];                                        //
  uint32_t i2c_address;                                        // 0x000004E0 
  uint8_t  anon007[24];                                        //
  union sysmon_2_flag flag;                                    // 0x000004FC 
  union sysmon_2_config_reg_0 config_reg_0;                    // 0x00000500 
  union sysmon_2_config_reg_1 config_reg_1;                    // 0x00000504 
  union sysmon_2_config_reg_2 config_reg_2;                    // 0x00000508 
  union sysmon_2_config_reg_3 config_reg_3;                    // 0x0000050C 
  union sysmon_2_config_reg_4 config_reg_4;                    // 0x00000510 
  union sysmon_2_analog_bus analog_bus;                        // 0x00000514 
  union sysmon_2_seqchsel0 seqchsel0;                          // 0x00000518 
  union sysmon_2_seqavg0 seqavg0;                              // 0x0000051C 
  union sysmon_2_seqchsel1 seqchsel1;                          // 0x00000520 
  union sysmon_2_seqchsel2 seqchsel2;                          // 0x00000524 
  union sysmon_2_seqavg1 seqavg1;                              // 0x00000528 
  union sysmon_2_seqavg2 seqavg2;                              // 0x0000052C 
  union sysmon_2_seqinmode0 seqinmode0;                        // 0x00000530 
  union sysmon_2_seqinmode1 seqinmode1;                        // 0x00000534 
  union sysmon_2_seqacq0 seqacq0;                              // 0x00000538 
  union sysmon_2_seqacq1 seqacq1;                              // 0x0000053C 
  uint32_t temperature_upper_threshold;                        // 0x00000540 
  uint32_t vccint_upper_threshold;                             // 0x00000544 
  uint32_t vccaux_upper_threshold;                             // 0x00000548 
  uint32_t over_temperature_upper_threshold;                   // 0x0000054C 
  uint32_t temperature_lower_threshold;                        // 0x00000550 
  uint32_t vccint_lower_threshold;                             // 0x00000554 
  uint32_t vccaux_lower_threshold;                             // 0x00000558 
  uint32_t over_temperature_lower_threshold;                   // 0x0000055C 
  uint32_t vccbram_upper_threshold;                            // 0x00000560 
  uint8_t  anon008[12];                                        //
  uint32_t vccbram_lower_threshold;                            // 0x00000570 
  uint8_t  anon009[12];                                        //
  uint32_t vuser0_upper_threshold;                             // 0x00000580 
  uint32_t vuser1_upper_threshold;                             // 0x00000584 
  uint32_t vuser2_upper_threshold;                             // 0x00000588 
  uint32_t vuser3_upper_threshold;                             // 0x0000058C 
  uint8_t  anon010[16];                                        //
  uint32_t vuser0_lower_threshold;                             // 0x000005A0 
  uint32_t vuser1_lower_threshold;                             // 0x000005A4 
  uint32_t vuser2_lower_threshold;                             // 0x000005A8 
  uint32_t vuser3_lower_threshold;                             // 0x000005AC 
  uint8_t  anon011[56];                                        //
  union sysmon_2_slowchsel0 slowchsel0;                        // 0x000005E8 
  union sysmon_2_slowchsel1 slowchsel1;                        // 0x000005EC 
  union sysmon_2_slowchsel2 slowchsel2;                        // 0x000005F0 
  uint8_t  anon012[12];                                        //
  uint32_t vuser0;                                             // 0x00000600 
  uint32_t vuser1;                                             // 0x00000604 
  uint32_t vuser2;                                             // 0x00000608 
  uint32_t vuser3;                                             // 0x0000060C 
  uint8_t  anon013[112];                                       //
  uint32_t max_vuser0;                                         // 0x00000680 
  uint32_t max_vuser1;                                         // 0x00000684 
  uint32_t max_vuser2;                                         // 0x00000688 
  uint32_t max_vuser3;                                         // 0x0000068C 
  uint8_t  anon014[16];                                        //
  uint32_t min_vuser0;                                         // 0x000006A0 
  uint32_t min_vuser1;                                         // 0x000006A4 
  uint32_t min_vuser2;                                         // 0x000006A8 
  uint32_t min_vuser3;                                         // 0x000006AC 
} __attribute((packed));

#endif // INCLUDE_SYSMON_2_BLOCK_H
