# This file's contents will be merged into the sn-stack main docker compose
# file to allow lab network connectivity to all services.
# Refer to https://docs.docker.com/compose/multiple-compose-files/merge/
networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.9${UNIQUE:-0}.0.0/16
          gateway: 10.9${UNIQUE:-0}.0.1
        - subnet: fdd5:b4c${UNIQUE:-0}:1237:763f::/64
          gateway: fdd5:b4c${UNIQUE:-0}:1237:763f::1
