services:
  smartnic-hw:
    hostname: smartnic-hw
    image: ${LABTOOLS_REGISTRY-}xilinx-labtools-docker:${LABTOOLS_TAG-v2021.2-latest}
    init: true
    user: root
    privileged: true
    restart: unless-stopped
    env_file:
      - ${SN_STACK_ROOT-.}/buildinfo.env
    tmpfs:
      - /status
    volumes:
      - debs:/debs
      - ${SN_STACK_ROOT-.}/smartnic-hw/scripts:/scripts:ro
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/test -e /status/ok"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 10s
    entrypoint:
      - /bin/bash
      - -c
      - -e
      - -o
      - pipefail
      - -x
      - |
        dpkg -i \
          /debs/esnet-smartnic1_1.0.0-$${SN_FW_VER}_amd64.deb
        /scripts/program_card.sh \
          localhost:3121 \
          "${HW_TARGET_SERIAL:-*}" \
          /usr/lib/firmware/esnet-smartnic/esnet-smartnic.bit \
          # FORCE
        if [ $$? ] ; then
          touch /status/ok
          sleep infinity
        fi

  smartnic-fw:
    hostname: smartnic-fw
    build:
      context: ${SN_STACK_ROOT-.}/smartnic-fw
      args:
        DOCKERHUB_PROXY: ${DOCKERHUB_PROXY-}
    depends_on:
      smartnic-hw:
        condition: service_healthy
    init: true
    user: root
    privileged: true
    restart: unless-stopped
    env_file:
      - ${SN_STACK_ROOT-.}/buildinfo.env
    environment:
      - REGIO_SELECT=$FPGA_PCIE_DEV.0
    volumes:
      - debs:/debs
      - /sys/bus/pci:/sys/bus/pci
      - /dev:/dev
    entrypoint:
      - /bin/bash
      - -c
      - -e
      - -o
      - pipefail
      - -x
      - |
        dpkg -i \
          /debs/esnet-smartnic1_1.0.0-$${SN_FW_VER}_amd64.deb \
          /debs/esnet-smartnic1-dbgsym_1.0.0-$${SN_FW_VER}_amd64.ddeb \
          /debs/esnet-smartnic-dev_1.0.0-$${SN_FW_VER}_amd64.deb
        setpci -s $FPGA_PCIE_DEV.0 COMMAND=0x2
        setpci -s $FPGA_PCIE_DEV.1 COMMAND=0x2
        sleep infinity

volumes:
  debs:
    driver_opts:
      type: none
      device: ${SN_STACK_ROOT-${PWD}}/debs/focal
      o: bind,ro
