tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/letsencrypt/{{ env `SN_TLS_PATH_PREFIX` }}{{ env `SN_TLS_FULLCHAIN` }}"
        keyFile:  "/etc/letsencrypt/{{ env `SN_TLS_PATH_PREFIX` }}{{ env `SN_TLS_KEY` }}"
