#---------------------------------------------------------------------------------------------------
__all__ = (
    'error_code_str'
)

from sn_p4_proto.v2 import ErrorCode

#---------------------------------------------------------------------------------------------------
ERROR_MAP = {
    # General error codes.
    ErrorCode.EC_OK: 'OK',

    # Batch error codes.
    ErrorCode.EC_UNKNOWN_BATCH_REQUEST: 'UNKNOWN_BATCH_REQUEST',
    ErrorCode.EC_UNKNOWN_BATCH_OP: 'UNKNOWN_BATCH_OP',

    # Device configuration error codes.
    ErrorCode.EC_INVALID_DEVICE_ID: 'INVALID_DEVICE_ID',

    # Pipeline configuration error codes.
    ErrorCode.EC_INVALID_PIPELINE_ID: 'INVALID_PIPELINE_ID',

    # Table configuration error codes.
    ErrorCode.EC_INVALID_TABLE_NAME: 'INVALID_TABLE_NAME',
    ErrorCode.EC_FAILED_CLEAR_ALL_TABLES: 'FAILED_CLEAR_ALL_TABLES',
    ErrorCode.EC_FAILED_CLEAR_TABLE: 'FAILED_CLEAR_TABLE',
    ErrorCode.EC_INVALID_ACTION_NAME: 'INVALID_ACTION_NAME',
    ErrorCode.EC_TABLE_RULE_TOO_FEW_MATCHES: 'TABLE_RULE_TOO_FEW_MATCHES',
    ErrorCode.EC_TABLE_RULE_TOO_MANY_MATCHES: 'TABLE_RULE_TOO_MANY_MATCHES',
    ErrorCode.EC_TABLE_RULE_TOO_FEW_ACTION_PARAMETERS: 'TABLE_RULE_TOO_FEW_ACTION_PARAMETERS',
    ErrorCode.EC_TABLE_RULE_TOO_MANY_ACTION_PARAMETERS: 'TABLE_RULE_TOO_MANY_ACTION_PARAMETERS',
    ErrorCode.EC_TABLE_RULE_INVALID_ACTION_PARAMETER_FORMAT: 'TABLE_RULE_INVALID_ACTION_PARAMETER_FORMAT',
    ErrorCode.EC_TABLE_RULE_MATCH_INVALID_KEY_FORMAT: 'TABLE_RULE_MATCH_INVALID_KEY_FORMAT',
    ErrorCode.EC_TABLE_RULE_MATCH_INVALID_MASK_FORMAT: 'TABLE_RULE_MATCH_INVALID_MASK_FORMAT',
    ErrorCode.EC_TABLE_RULE_MATCH_INVALID_PREFIX_LENGTH: 'TABLE_RULE_MATCH_INVALID_PREFIX_LENGTH',
    ErrorCode.EC_TABLE_RULE_MATCH_RANGE_LOWER_TOO_BIG: 'TABLE_RULE_MATCH_RANGE_LOWER_TOO_BIG',
    ErrorCode.EC_TABLE_RULE_MATCH_RANGE_UPPER_TOO_BIG: 'TABLE_RULE_MATCH_RANGE_UPPER_TOO_BIG',
    ErrorCode.EC_UNKNOWN_TABLE_RULE_MATCH_TYPE: 'UNKNOWN_TABLE_RULE_MATCH_TYPE',
    ErrorCode.EC_FAILED_INSERT_TABLE_RULE: 'FAILED_INSERT_TABLE_RULE',
    ErrorCode.EC_FAILED_DELETE_TABLE_RULE: 'FAILED_DELETE_TABLE_RULE',
    ErrorCode.EC_TABLE_RULE_FIELD_SPEC_OVERFLOW: 'TABLE_RULE_FIELD_SPEC_OVERFLOW',
    ErrorCode.EC_TABLE_RULE_FIELD_SPEC_FORMAT_INVALID: 'TABLE_RULE_FIELD_SPEC_FORMAT_INVALID',
    ErrorCode.EC_TABLE_RULE_FIELD_SPEC_UNKNOWN_TYPE: 'TABLE_RULE_FIELD_SPEC_UNKNOWN_TYPE',
    ErrorCode.EC_TABLE_RULE_FIELD_SPEC_SIZE_MISMATCH: 'TABLE_RULE_FIELD_SPEC_SIZE_MISMATCH',
    ErrorCode.EC_TABLE_RULE_PACK_KEY_TOO_BIG: 'TABLE_RULE_PACK_KEY_TOO_BIG',
    ErrorCode.EC_TABLE_RULE_PACK_MASK_TOO_BIG: 'TABLE_RULE_PACK_MASK_TOO_BIG',
    ErrorCode.EC_TABLE_RULE_PACK_PARAMS_TOO_BIG: 'TABLE_RULE_PACK_PARAMS_TOO_BIG',
    ErrorCode.EC_TABLE_RULE_MATCH_INVALID_FORMAT: 'TABLE_RULE_MATCH_INVALID_FORMAT',
    ErrorCode.EC_TABLE_RULE_MATCH_MASK_TOO_WIDE: 'TABLE_RULE_MATCH_MASK_TOO_WIDE',
    ErrorCode.EC_TABLE_RULE_MATCH_INVALID_BITFIELD_MASK: 'TABLE_RULE_MATCH_INVALID_BITFIELD_MASK',
    ErrorCode.EC_TABLE_RULE_MATCH_INVALID_CONSTANT_MASK: 'TABLE_RULE_MATCH_INVALID_CONSTANT_MASK',
    ErrorCode.EC_TABLE_RULE_MATCH_INVALID_PREFIX_MASK: 'TABLE_RULE_MATCH_INVALID_PREFIX_MASK',
    ErrorCode.EC_TABLE_RULE_MATCH_INVALID_RANGE_MASK: 'TABLE_RULE_MATCH_INVALID_RANGE_MASK',
    ErrorCode.EC_TABLE_RULE_MATCH_INVALID_UNUSED_MASK: 'TABLE_RULE_MATCH_INVALID_UNUSED_MASK',
    ErrorCode.EC_TABLE_RULE_MATCH_KEY_TOO_BIG: 'TABLE_RULE_MATCH_KEY_TOO_BIG',
    ErrorCode.EC_TABLE_RULE_MATCH_MASK_TOO_BIG: 'TABLE_RULE_MATCH_MASK_TOO_BIG',
    ErrorCode.EC_TABLE_RULE_INVALID_TABLE_NAME: 'TABLE_RULE_INVALID_TABLE_NAME',
    ErrorCode.EC_TABLE_RULE_INVALID_TABLE_CONFIG: 'TABLE_RULE_INVALID_TABLE_CONFIG',
    ErrorCode.EC_TABLE_RULE_INVALID_ACTION_FOR_TABLE: 'TABLE_RULE_INVALID_ACTION_FOR_TABLE',
    ErrorCode.EC_TABLE_RULE_PARAM_INVALID_FORMAT: 'TABLE_RULE_PARAM_INVALID_FORMAT',
    ErrorCode.EC_TABLE_RULE_PARAM_SPEC_OVERFLOW: 'TABLE_RULE_PARAM_SPEC_OVERFLOW',
    ErrorCode.EC_TABLE_RULE_PARAM_SPEC_SIZE_MISMATCH: 'TABLE_RULE_PARAM_SPEC_SIZE_MISMATCH',
    ErrorCode.EC_TABLE_RULE_PARAM_TOO_BIG: 'TABLE_RULE_PARAM_TOO_BIG',

    # Server configuration error codes.
    ErrorCode.EC_SERVER_FAILED_GET_TIME: 'SERVER_FAILED_GET_TIME',
}

def error_code_str(ec):
    return ERROR_MAP.get(ec, 'UNKNOWN')
